var myFullName;
console.log(myFullName);
var myFullName="Tejashri Raut";
console.log(myFullName);
var myFullName="Tejashri Manohar Raut";
console.log(myFullName);
var myLove="I Love only JS";
console.log(myLove);
var firstName="Tejashri";
console.log(firstName);
var lastName="Raut";
console.log(lastName);
var age="24";
console.log(age);
var address="Sangola";
console.log(address);
var pincode="413307";
console.log(pincode);
var gender="female";
console.log(gender);
var isMarried="yes";
console.log(isMarried);
